/**
 * Token generated by concatenating username and password with `:` character within a base64 encoded string.
 *
 * @param  {String} user
 * User identifier.
 *
 * @param  {String} pass
 * Password.
 *
 * @return {String}
 * Base64 encoded authentication token.
 */

export default function token (user: string, pass: string) {
  return base64([user, pass].join(':'))
}

function base64(str: string) {
  return Buffer.from(str).toString('base64')
}